// Generates servicenow/src/D365CCIcons.js from Microsoft's Fluent System Icons (MIT licensed):
// https://github.com/microsoft/fluentui-system-icons
// Usage: node deploy/tools/fetch-icons.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const SIZE = 20;

// [key, fluent icon name, style]
const ICONS = [
    ['call_inbound', 'call_inbound', 'regular'],
    ['bot', 'bot', 'regular'],
    ['queue', 'people_queue', 'regular'],
    ['headset', 'headset', 'regular'],
    ['check', 'checkmark_circle', 'filled'],
    ['live', 'record', 'filled'],
    ['play', 'play', 'filled'],
    ['transcript', 'document_text', 'regular'],
    ['open', 'open', 'regular'],
    ['timer', 'timer', 'regular'],
    ['mic', 'mic', 'regular'],
    ['phone', 'phone', 'regular'],
    ['sparkle', 'sparkle', 'regular'],
    ['lightbulb', 'lightbulb', 'regular'],
    ['chart', 'data_bar_vertical', 'regular'],
    ['happy', 'emoji_laugh', 'regular'],
    ['smile', 'emoji_smile_slight', 'regular'],
    ['neutral', 'emoji_meh', 'regular'],
    ['sad', 'emoji_sad', 'regular'],
    ['angry', 'emoji_angry', 'regular']
];

const title = (n) => n.split('_').map((w) => w[0].toUpperCase() + w.slice(1)).join('%20');

const out = {};
for (const [key, name, style] of ICONS) {
    const url = `https://raw.githubusercontent.com/microsoft/fluentui-system-icons/main/assets/${title(name)}/SVG/ic_fluent_${name}_${SIZE}_${style}.svg`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
    const svg = await res.text();
    // keep only the drawing elements; the colour is applied at render time
    const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\sfill="#[0-9a-fA-F]{3,8}"/g, '').trim();
    out[key] = inner;
    console.log('ok', key);
}

const js = `// GENERATED by deploy/tools/fetch-icons.mjs from Microsoft Fluent System Icons (MIT):
// https://github.com/microsoft/fluentui-system-icons. Do not edit by hand.
var D365CCIcons = Class.create();
D365CCIcons.prototype = {
    initialize: function () {},

    PATHS: ${JSON.stringify(out, null, 8).replace(/\n    /g, '\n    ')},

    // Returns an <img> with a data-URI SVG so it survives rich-text sanitizing and takes any colour.
    img: function (name, size, color) {
        var inner = this.PATHS[name];
        if (!inner) return '';
        var s = size || 16;
        var svg = '<svg xmlns="http://www.w3.org/2000/svg" width="' + s + '" height="' + s + '" viewBox="0 0 ${SIZE} ${SIZE}" fill="' + (color || '#424242') + '">' + inner + '</svg>';
        return '<img alt="" width="' + s + '" height="' + s + '" style="display:block;border:0;" src="data:image/svg+xml;utf8,' + encodeURIComponent(svg) + '"/>';
    },

    type: 'D365CCIcons'
};
`;
fs.writeFileSync(path.join(root, 'servicenow', 'src', 'D365CCIcons.js'), js);
console.log('wrote servicenow/src/D365CCIcons.js (' + js.length + ' bytes)');
